[package]
authors = ["Wang Zishi <ynh.2@outlook.com>"]
edition = "2021"
license = "MIT OR Apache-2.0"
name = "esp_rust_app"
version = "0.1.0"

[dependencies]
esp-backtrace = {version = "0.5.0", features = ["esp32c3", "panic-handler", "print-uart"]}
esp32c3-hal = "0.5.0"
riscv-rt = {version = "0.11", optional = true}

[features]
default = ["rt"]
rt = ["riscv-rt"]
